# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 295ca46b1baa56fc8dc7d049e1c962c3cf07dac0569d7593585527956bef7a53dce70620106e7dcc1b6d2351adc31af07fab8c49fc40762b993ace2abd2c9b8a

test:
  secret_key_base: e8434586d71bacb65c42bcb80ac9d396be82d318395d988fa32570aa662570ff07f2a27578167b3819406f1e1f4748ee4f71b9898d19607256b831f57ccfd56f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
